# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xI7axc_q6-n7UPhErmo7ARZyvheVlYbt
"""

! pip install --upgrade fastai

! pip install -U fastcore fastai

from fastai.text.all import *

path = untar_data(URLs.IMDB_SAMPLE)
path.ls()

df = pd.read_csv(path/'texts.csv')
df.head(2)

df['text'][1]

imdb_lm = DataBlock(blocks=(TextBlock.from_df('text', is_lm=True),),
                    get_x=ColReader('text'),
                    splitter=RandomSplitter())

dbunch_lm = imdb_lm.dataloaders(df)

bs=128

path = untar_data(URLs.IMDB)
path.ls()

imdb_lm = DataBlock(blocks=(TextBlock.from_folder(path, is_lm=True),),
                    get_items=partial(get_text_files, folders=['train', 'test', 'unsup']),
                    splitter=RandomSplitter(0.1))

dbunch_lm = imdb_lm.dataloaders(path, path=path, bs=bs, seq_len=80)

learn = language_model_learner(dbunch_lm, AWD_LSTM, drop_mult=0.3, metrics=[accuracy, Perplexity()])

learn.fit_one_cycle(1, 2e-2, moms=(0.8,0.7,0.8))

learn.unfreeze()

learn.fit_one_cycle(2, 2e-3, moms=(0.8,0.7,0.8))

learn.save('fine_tuned')

from google.colab import drive

drive.mount('/content/drive')

path = Path("/content/drive/My Drive/") ; path

learn.save(path/'fine_tuned')

learn.load('/content/drive/My Drive/fine_tuned')

TEXT = "I liked Trump because"
N_WORDS = 15
N_SENTENCES = 1

print("\n".join(learn.predict(TEXT, N_WORDS, temperature=0.75) for _ in range(N_SENTENCES)))

learn.save_encoder(path/'fine_tuned_enc')



def read_tokenized_file(f): return L(f.read().split(' '))

imdb_clas = DataBlock(blocks=(TextBlock.from_folder(path, vocab=dbunch_lm.vocab),CategoryBlock),
                      get_x=read_tokenized_file,
                      get_y = parent_label,
                      get_items=partial(get_text_files, folders=['train', 'test']),
                      splitter=GrandparentSplitter(valid_name='test'))

dbunch_clas = imdb_clas.dataloaders(path, path=path, bs=bs, seq_len=80)

learn = text_classifier_learner(dbunch_clas, AWD_LSTM, drop_mult=0.5, metrics=accuracy)
learn.load_encoder('/content/drive/My Drive/fine_tuned_enc')

learn.fit_one_cycle(1, 2e-2, moms=(0.8,0.7, 0.8))

learn.freeze_to(-2)
learn.fit_one_cycle(1, slice(1e-2/(2.6**4),1e-2), moms=(0.8,0.7, 0.8))

learn.freeze_to(-3)
learn.fit_one_cycle(1, slice(5e-3/(2.6**4),5e-3),moms=(0.8,0.7, 0.8))

learn.unfreeze()
learn.fit_one_cycle(2, slice(1e-3/(2.6**4),1e-3), moms=(0.8,0.7, 0.8))

learn.save('/content/drive/My Drive/fine_tuned_classifier_no16')

learn.save_encoder('/content/drive/My Drive/fine_tuned_enc_classifier_no16')

learn.predict("I think Trump wasn't as good as he thinks he was. He lost clearly")

learn.predict("I think Trump was great tonight. I loved how confident he was!")

learn.load('/content/drive/My Drive/fine_tuned_classifier_no16')

